version: '3.8'
services:
  nginx:
    image: nginx:alpine
    container_name: pasteau-nginx
    ports:
      - "8000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html/frontend
      - ./data:/usr/share/nginx/html/data
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: pasteau-app